# Generated by Django 6.0.6 on 2026-06-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('cobrada', 'Cobrada')], default='pendiente', max_length=20),
        ),
    ]
