# Generated by Django 6.0.6 on 2026-06-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_estado_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha_cobro',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
