# Generated by Django 6.0.6 on 2026-07-31 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_movimientostock_lote'),
        ('ventas', '0003_venta_fecha_cobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='autorizacion_veterinaria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='inventario.lotestock'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='stock_descontado',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('completada', 'Completada'), ('cancelada', 'Cancelada')], default='completada', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Débito'), ('credito', 'Crédito'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
