# Generated by Django 6.0.6 on 2026-06-21 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
        ('mascotas', '0002_mascota_alergias_mascota_grupo_sanguineo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioHigiene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_higiene', to='mascotas.mascota')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_higiene_registrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
