# Generated by Django 6.0.6 on 2026-06-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_serviciohigiene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciohigiene',
            name='tipo_servicio',
            field=models.CharField(choices=[('baño', 'Baño'), ('peluqueria', 'Peluquería'), ('baño_y_corte', 'Baño y corte'), ('corte_uñas', 'Corte de uñas'), ('limpieza_oidos', 'Limpieza de oídos'), ('baño_antipulgas', 'Baño antipulgas')], max_length=50),
        ),
    ]
