# Generated by Django 6.0.6 on 2026-06-22 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_alter_serviciohigiene_tipo_servicio'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciohigiene',
            name='tipo_servicio',
        ),
        migrations.AddField(
            model_name='serviciohigiene',
            name='servicio',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_higiene', to='servicios.servicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviciohigiene',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
