# Generated by Django 6.0.6 on 2026-06-22 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_remove_serviciohigiene_tipo_servicio_and_more'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='consulta',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='servicios.servicio'),
            preserve_default=False,
        ),
    ]
