# Generated by Django 6.0.6 on 2026-06-22 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0005_consulta_precio_consulta_servicio'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacunacion',
            name='vacuna',
        ),
        migrations.AddField(
            model_name='vacunacion',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vacunacion',
            name='servicio',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='vacunaciones', to='servicios.servicio'),
            preserve_default=False,
        ),
    ]
