# Generated by Django 6.0.6 on 2026-06-22 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0006_remove_vacunacion_vacuna_vacunacion_precio_and_more'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cirugia',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='cirugia',
            name='tipo_cirugia',
        ),
        migrations.AddField(
            model_name='cirugia',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='servicio',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='cirugias', to='servicios.servicio'),
            preserve_default=False,
        ),
    ]
