# Generated by Django 6.0.6 on 2026-06-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0007_remove_cirugia_costo_remove_cirugia_tipo_cirugia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
