# Generated by Django 6.0.6 on 2026-06-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0008_consulta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacunacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aplicada', 'Aplicada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
