# Generated by Django 6.0.6 on 2026-06-22 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0009_vacunacion_estado'),
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='turno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulta', to='turnos.turno'),
        ),
    ]
