# Generated by Django 6.0.6 on 2026-06-22 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0010_consulta_turno'),
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirugia',
            name='turno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cirugia', to='turnos.turno'),
        ),
        migrations.AddField(
            model_name='serviciohigiene',
            name='turno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicio_higiene', to='turnos.turno'),
        ),
        migrations.AddField(
            model_name='vacunacion',
            name='turno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacunacion', to='turnos.turno'),
        ),
    ]
