# Generated by Django 6.0.6 on 2026-06-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientostock',
            name='motivo',
            field=models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta'), ('vacunacion', 'Vacunación'), ('consulta', 'Consulta'), ('cirugia', 'Cirugía'), ('higiene', 'Higiene'), ('ajuste_manual', 'Ajuste manual')], max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('vacuna', 'Vacuna'), ('medicamento', 'Medicamento'), ('alimento', 'Alimento'), ('juguete', 'Juguete'), ('accesorio', 'Accesorio'), ('higiene', 'Higiene'), ('insumo_medico', 'Insumo médico'), ('antiparasitario', 'Antiparasitario'), ('otro', 'Otro')], max_length=30),
        ),
    ]
