# Generated by Django 6.0.6 on 2026-06-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_movimientostock_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('comercial', 'Comercial'), ('interno', 'Interno'), ('ambos', 'Comercial e Interno')], max_length=20),
        ),
    ]
