# Generated by Django 6.0.6 on 2026-06-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_producto_tipo_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_compra_referencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
