# Generated by Django 6.0.6 on 2026-07-31 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_producto_precio_compra_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=100)),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventario.producto')),
            ],
            options={
                'ordering': ['fecha_vencimiento', 'numero_lote'],
                'constraints': [models.UniqueConstraint(fields=('producto', 'numero_lote'), name='lote_unico_por_producto')],
            },
        ),
    ]
