# Generated by Django 6.0.6 on 2026-07-31 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_lotestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.lotestock'),
        ),
    ]
