# Generated by Django 6.0.6 on 2026-06-22 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('egresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_caja', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
