# Generated by Django 6.0.6 on 2026-06-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_cierrecaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='motivo',
            field=models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra'), ('servicio_clinico', 'Servicio clínico'), ('ajuste_manual', 'Ajuste manual')], max_length=30),
        ),
    ]
