# Generated by Django 6.0.6 on 2026-08-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False),
        ),
    ]
