# Generated by Django 6.0.6 on 2026-06-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compra_numero_comprobante_compra_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada')], default='pendiente', max_length=20),
        ),
    ]
