# Generated by Django 6.0.6 on 2026-06-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_compra_estado_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
