# Generated by Django 6.0.6 on 2026-06-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('consulta', 'Consulta'), ('vacunacion', 'Vacunación'), ('cirugia', 'Cirugía'), ('higiene', 'Higiene'), ('estudio', 'Estudio'), ('otro', 'Otro')], max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
            ],
        ),
    ]
